fixtures:
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppi: "git://github.com/example42/puppi.git"
  symlinks:
    iptables: "#{source_dir}"
